import { REGULATORY_STATEMENT, UNIT_OF_ANALYSIS } from '../analysis/constants';
import type { Attribution } from '../analysis/attribution';
import type { AnalysisResult, OligoAnalysis } from '../analysis/run';
import type { PositionStat } from '../analysis/profile';
import { getPathogen } from '../registry';
import { referenceFetchedAt } from '../../data/references';
import { methodsParagraph, TOOL_NAME, TOOL_VERSION } from './methods';

/**
 * RFC 4180 says CRLF, and Excel, Numbers and Google Sheets all accept it on
 * every platform. Using bare LF would work too but only by everyone's
 * tolerance rather than by the spec.
 */
const ROW_SEPARATOR = '\r\n';

/**
 * The characters Excel and Google Sheets treat as "this cell is a formula"
 * when a file is opened. A tab or a carriage return leads because both are
 * stripped before the parse, exposing whatever follows.
 */
const FORMULA_LEADERS = ['=', '+', '-', '@', '\t', '\r', '\n'];

/**
 * DECISION: a value that begins with a formula character is emitted with a
 * leading apostrophe. It is not rejected, and it is not dropped.
 *
 * Three fields in these exports carry values this app did not choose: the
 * oligo name (typed by the user, or lifted from a pasted FASTA header), and
 * the lineage and country values that come back from LAPIS. An oligo named
 * `=HYPERLINK("http://…","payroll.xlsx")` would otherwise travel through the
 * export and execute the moment a colleague opened the file.
 *
 * The cost is real and is paid by every honest value too: a primer legitimately
 * named `-70C stock` exports as `'-70C stock`. Spreadsheets hide the apostrophe
 * and show the original text, but anything reading the CSV as text -- a script,
 * `git diff`, a person opening it in an editor -- sees the extra character. The
 * export therefore says so in its comment header, so the reader can tell an
 * apostrophe this export added from one the user typed.
 *
 * The alternative -- refusing to export such a row, or blanking the value --
 * loses data and moves the problem to a place where it is discovered later.
 * Between altering a value visibly and stating that alteration, and silently
 * shipping something executable, the first is the smaller harm.
 *
 * Applied to text cells only. Every numeric cell in these files is generated by
 * this app, is non-negative, and would only be made worse by an apostrophe.
 */
function defuse(value: string): string {
  const first = value[0];
  return first !== undefined && FORMULA_LEADERS.includes(first) ? `'${value}` : value;
}

/** RFC 4180 quoting: quote if the value carries a delimiter, a quote or a line break. */
function quote(value: string): string {
  return /[",\r\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

/**
 * A cell holding text. Guarded, then quoted -- in that order, because a
 * spreadsheet evaluates a formula inside a quoted field just as happily as one
 * outside it, so the apostrophe has to be inside the quotes.
 */
function text(value: string): string {
  return quote(defuse(value));
}

function count(value: number): string {
  return String(value);
}

function flag(value: boolean): string {
  return value ? 'true' : 'false';
}

/**
 * A rate, or an empty cell when there is no rate to state.
 *
 * `null` means *nothing was assessable*, which is the opposite of zero, so it
 * must never be written as `0` -- and not as the word `null` or `NaN` either,
 * both of which a spreadsheet shows as text in a numeric column.
 *
 * Six significant figures rather than six decimal places: a genuinely non-zero
 * rate of 1 in 3,000,000 rounds to `0.000000` at six decimals, which is the
 * same lie in a different disguise.
 */
function rate(value: number | null): string {
  return value === null ? '' : String(Number(value.toPrecision(6)));
}

const topValue = (attribution: Attribution): string => attribution.rows[0]?.value ?? '';
const topCount = (attribution: Attribution): string => {
  const row = attribution.rows[0];
  return row === undefined ? '' : count(row.count);
};

/** A comment line can never be allowed to become two comment lines. */
function comment(line: string): string {
  return `# ${line.replace(/[\r\n]+/g, ' ')}`;
}

/**
 * The block every export opens with.
 *
 * The unit of analysis is the very first line, before anything else, because
 * it is the one sentence that makes the columns mean what they say -- and
 * because someone who opens this in a spreadsheet a year from now reads line 1
 * and stops.
 */
function header(result: AnalysisResult, what: string, emptyCellNote: string): string[] {
  const cfg = getPathogen(result.pathogenId);
  const { scope } = result;
  const countries = scope.countries.length > 0 ? scope.countries.join('; ') : 'all';
  const lineages = scope.lineages.length > 0 ? scope.lineages.join('; ') : 'all';

  return [
    comment(UNIT_OF_ANALYSIS),
    comment(
      `${TOOL_NAME} ${TOOL_VERSION} — ${what} export — ${cfg.label} — generated ${result.generatedAt}`,
    ),
    comment(`Source: ${cfg.lapisBaseUrl}, data version ${result.dataVersion}. ${cfg.attribution}`),
    comment(
      `Reference genome retrieved from the same instance on ${referenceFetchedAt(result.pathogenId)}.`,
    ),
    comment(
      `Scope: collection dates ${scope.dateFrom} to ${scope.dateTo}; countries: ${countries};` +
        ` ${cfg.lineageLabel}: ${lineages}; ${result.nScope} sequences in scope.`,
    ),
    comment(emptyCellNote),
    comment(
      'A value that began with = + - @ a tab or a carriage return is written with a leading' +
        ' apostrophe, so a spreadsheet shows it as text instead of running it as a formula.' +
        ' That apostrophe was added by this export and is not part of the value.',
    ),
    comment(REGULATORY_STATEMENT),
  ];
}

const SUMMARY_COLUMNS = [
  // The first twelve are fixed by the plan, in this order.
  'oligo', 'role', 'segment', 'start', 'end', 'strand',
  'n_scope', 'n_full_coverage', 'n_mismatch', 'mismatch_fraction', 'coverage_gap', 'severity',
  'coverage_gap_fraction', 'severity_score', 'sufficient_data',
  'top_lineage', 'top_lineage_n', 'top_country', 'top_country_n', 'sequence',
];

const SUMMARY_EMPTY_CELL_NOTE =
  'An empty cell means the value could not be computed; it never means zero.' +
  ' mismatch_fraction is empty exactly when n_full_coverage is 0 — no sequence in scope could be' +
  ' assessed at that site, so there is no rate to report.';

function summaryRow(oligo: OligoAnalysis): string {
  const m = oligo.metrics;
  return [
    text(oligo.name),
    oligo.role,
    text(oligo.site.segment),
    count(oligo.site.start),
    count(oligo.site.end),
    oligo.site.strand,
    count(m.nScope),
    count(m.nFullCoverage),
    count(m.nMismatch),
    rate(m.mismatchFraction),
    count(m.coverageGap),
    oligo.severity.level,
    rate(m.coverageGapFraction),
    rate(oligo.severity.score),
    flag(m.sufficientData),
    text(topValue(oligo.lineage)),
    topCount(oligo.lineage),
    text(topValue(oligo.country)),
    topCount(oligo.country),
    text(oligo.sequence),
  ].join(',');
}

/**
 * One row per oligo: the headline numbers.
 *
 * Every rate sits in the same row as the counts it was computed from
 * (Global Constraint 6). A file that carried `mismatch_fraction` without
 * `n_full_coverage` beside it would be a percentage without its N the moment
 * anyone pasted a column into a slide.
 */
export function toSummaryCsv(result: AnalysisResult): string {
  return [
    ...header(result, 'per-oligo summary', SUMMARY_EMPTY_CELL_NOTE),
    SUMMARY_COLUMNS.join(','),
    ...result.oligos.map(summaryRow),
  ].join(ROW_SEPARATOR);
}

const POSITION_COLUMNS = [
  'oligo', 'role', 'segment', 'ref_pos', 'oligo_index', 'oligo_base', 'plus_strand_base',
  'ref_base', 'distance_from_3prime', 'coverage', 'coverage_is_inferred',
  'effective_denominator', 'mismatch_count', 'substitution_count', 'deletion_count',
  'mismatch_fraction', 'reference_is_ambiguous',
];

const POSITION_EMPTY_CELL_NOTE =
  'An empty cell means the value could not be computed; it never means zero.' +
  ' coverage is empty where LAPIS reported no per-position coverage, and coverage_is_inferred is' +
  ' then true because the window denominator was substituted (Global Constraint 5: no row at a' +
  ' position is not evidence of conservation). mismatch_fraction is empty where' +
  ' effective_denominator is 0, and where reference_is_ambiguous is true, because no allele at' +
  ' such a position can be judged a mismatch.';

function positionRow(oligo: OligoAnalysis, p: PositionStat): string {
  const assessable = p.effectiveDenominator > 0 && !p.referenceIsAmbiguous;
  return [
    text(oligo.name),
    oligo.role,
    text(oligo.site.segment),
    count(p.refPos),
    count(p.oligoIndex),
    p.oligoBase,
    p.plusStrandBase,
    p.refBase,
    count(p.distanceFrom3Prime),
    p.coverage === null ? '' : count(p.coverage),
    flag(p.coverageIsInferred),
    count(p.effectiveDenominator),
    count(p.mismatchCount),
    count(p.substitutionCount),
    count(p.deletionCount),
    assessable ? rate(p.mismatchFraction) : '',
    flag(p.referenceIsAmbiguous),
  ].join(',');
}

/** One row per oligo x position: the per-base detail behind each headline. */
export function toPositionCsv(result: AnalysisResult): string {
  return [
    ...header(result, 'per-position profile', POSITION_EMPTY_CELL_NOTE),
    POSITION_COLUMNS.join(','),
    ...result.oligos.flatMap((oligo) => oligo.profile.map((p) => positionRow(oligo, p))),
  ].join(ROW_SEPARATOR);
}

/**
 * The whole analysis, plus the provenance and copy that the CSV comment header
 * carries, so a JSON reader is never worse informed than a spreadsheet reader.
 *
 * `result` is embedded verbatim rather than flattened: `null` survives as
 * `null` here, which is the one representation that cannot be misread as zero.
 */
export function toJsonExport(result: AnalysisResult): string {
  const cfg = getPathogen(result.pathogenId);
  return JSON.stringify(
    {
      tool: TOOL_NAME,
      version: TOOL_VERSION,
      unitOfAnalysis: UNIT_OF_ANALYSIS,
      regulatoryStatement: REGULATORY_STATEMENT,
      methods: methodsParagraph(result),
      source: {
        lapisBaseUrl: cfg.lapisBaseUrl,
        dataVersion: result.dataVersion,
        attribution: cfg.attribution,
        referenceFetchedAt: referenceFetchedAt(result.pathogenId),
      },
      result,
    },
    null,
    2,
  );
}
